[package]
name = "cain_ls"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A simple ls command implementation in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
